// The scenery SVGs are design-tool exports: a single full-res raster embedded
// as base64 inside a <pattern>, cropped to the viewBox via a <use> matrix.
// librsvg refuses to parse the 10 MB base64 line, so instead of rendering the
// SVG we extract the embedded raster and reproduce the crop with sharp, then
// emit web-sized WebP + a tiny inlined blur placeholder (LQIP) for next/image.
// Plain raster sources (raw: true) skip extraction and go straight to sharp.
// Run with: npm run optimize:images
import sharp from "sharp";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const pub = (p) => path.join(ROOT, "public", p);

const jobs = [
  {
    name: "hero",
    src: pub("scenery/boat_landing.svg"),
    out: pub("scenery/hero.webp"),
    width: 2400,
    quality: 72,
  },
  {
    name: "boat",
    src: pub("scenery/boat.svg"),
    out: pub("scenery/boat.webp"),
    width: 1400,
    quality: 74,
  },
  {
    name: "avatar",
    src: pub("about_icons/spotify_pfp.svg"),
    out: pub("about_icons/avatar.webp"),
    width: 256,
    quality: 80,
  },
  {
    name: "hitl",
    src: pub("scenery/nick_hitl.jpg"),
    out: pub("scenery/hitl.webp"),
    width: 1800,
    quality: 76,
    raw: true,
  },
];

// Pull the embedded raster + the pattern crop out of a Figma-style SVG export.
async function extractCroppedRaster(svgPath) {
  const svg = await readFile(svgPath, "utf8");

  const dataMatch = svg.match(/data:image\/(?:png|jpe?g|webp);base64,([^"']+)/);
  if (!dataMatch) throw new Error(`no embedded raster in ${svgPath}`);
  const raster = Buffer.from(dataMatch[1], "base64");

  const m = svg.match(/transform="matrix\(([^)]+)\)"/);
  if (!m) return sharp(raster); // no crop info — use the whole image
  const [a, , , d, e, f] = m[1]
    .trim()
    .split(/[\s,]+/)
    .map(Number);

  const { width: imgW, height: imgH } = await sharp(raster).metadata();
  // device-visible window maps back to image pixels: origin -translate/scale,
  // size 1/scale (scale here is a*boxW == device px per image px == 1:1).
  const left = Math.max(0, Math.round(-e / a));
  const top = Math.max(0, Math.round(-f / d));
  const width = Math.min(Math.round(1 / a), imgW - left);
  const height = Math.min(Math.round(1 / d), imgH - top);
  return sharp(raster).extract({ left, top, width, height });
}

const blurs = {};
for (const job of jobs) {
  const base = job.raw
    ? sharp(job.src).rotate()
    : await extractCroppedRaster(job.src);
  await base
    .clone()
    .resize({ width: job.width, withoutEnlargement: true })
    .webp({ quality: job.quality })
    .toFile(job.out);

  const blurBuf = await base
    .clone()
    .resize({ width: 20 })
    .webp({ quality: 30 })
    .toBuffer();
  blurs[job.name] = `data:image/webp;base64,${blurBuf.toString("base64")}`;
  console.log(`✓ ${job.name} -> ${path.relative(ROOT, job.out)}`);
}

const dataDir = path.join(ROOT, "src/data");
await mkdir(dataDir, { recursive: true });
const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Tiny inlined blur placeholders (LQIP) for next/image placeholder="blur".
export const blurDataURLs = {
${Object.entries(blurs)
  .map(([k, v]) => `  ${k}: "${v}",`)
  .join("\n")}
} as const;
`;
await writeFile(path.join(dataDir, "images.ts"), ts);
console.log("✓ wrote src/data/images.ts");
