// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Tiny inlined blur placeholders (LQIP) for next/image placeholder="blur".
export const blurDataURLs = {
  hero: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAAwAPxFysFAsJqSisAgBgCIJZQC7AB6J3E+tjqS8gAAA/Fpcqzr18hEU+7gPA7mQXOOGgFF6aAVOVd3yUoDyaRorA/WmadIb4IN7MoIoAAAA",
  boat: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwBACdASoUABQAPxF8s1QsJ6QjKAqpgCIJYwDCgA9omwmxIQIV/FeLxdfUPHLtFMAA/o03o+9STLnCYYPD0PbAElhgQ8ya7IYKadss0CPO2AzrD0TETNcHCy8RSiBrDl07oJyxKpwwqHGsZzcUWK7l5DnGYIbWse3iz4QQAAA=",
  avatar: "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACwBACdASoUABQAPxGAt1WsJ6UjKAgBgCIJZQDGfBDNdfTb4OEn2oS0tWOWjoaAAP40b0dKaQ7ofp5+c/PK9xih/WZgH0bn9nCjYJ5lOGIpiiDKPRBg5eEGuWlQeqjtFljHLSif8kOCYUyvIdujWsOzPMSwE3qxBEiZ6wgjAwAXydUZcWl9dUzHdInt/MR28RXuxPDohFVpfrBL8VCX9QAAAAA=",
  hitl: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoUAA0APxFwsFAsJiSisAgBgCIJYgCdMoABmUkyOg3UpX1wAAD7+wbihkpbB9tHMjKyT5jCSM4i4XtZyvcduGsvH0woDz4lhfM5yr+1/Qdihtx/eEABKwtP59dtk3MixEVPSjQbDoBK9Dj4AAA=",
} as const;
